### PR TITLE
#221 - Switch to async/await and major Lasso refactors

### PR DESCRIPTION
**Pull request by austinkelleher**
To summarize the changes:

- Almost all of the code has been switched to async/await. Some of it can't really quite go fully async/await yet because it's bound by streaming code.
- `lasso-image`, `lasso-resolve-css-urls`, `lasso-minify-css`, `lasso-minify-js` have all been moved into Lasso.
- Remove lasso taglib v2
- Most async API functions only support promises
- jshint does not support async/await syntax, so I switched to eslint

The functional changes resulted in **~1500** lines of code reduction

I split the PR into 3 main commits. One that has most of the functional changes, the second that contains the external Lasso modules being pulled into core, and the 3rd being eslint fixes.

Most of the functional changes are in this commit: https://github.com/lasso-js/lasso/pull/222/commits/b7d65ac971ac13a273e50ad64457c281b420aea0

Ultimately, I think this may be a good time to change the name of Lasso to something else. These changes are major breaking and will only support Node 8+.

### CODE REVIEW

**Comment by philidem** [comment]
I'm glad you didn't have to change many files :)

**Comment by philidem** [comment]
I agree -- good time to start discussing rename.

**Comment by philidem** [comment]
Also, maybe in future PR, switch to using `let`/`const`

**Comment by philidem** [comment]
Did you verify error handling with a outermost `.catch(...)` clause? Just want to make sure errors don't get eaten.

**Comment by austinkelleher** [comment]
As a follow-up, I want to actually revisit a lot of this code and refactor. This would include `let`/`const`, removing a lot of old modules that aren't relevant anymore, rethinking some algorithms, and _perhaps_ remove some streaming support. The streaming code is pretty complicated and I think only useful in a few scenarios.

**Pull request merged**
