### PR TITLE
routePrefix fix

### PR DESCRIPTION
**Pull request by FiW**
urlPrefix can be full url

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
@austinkelleher do you mind reviewing this?

**Comment by patrick-steele-idem** [comment]
Thanks for the PR Alexander. Can you please more details on the problem this change solves? Maybe some sample code?

**Comment by FiW** [comment]
I using marko & lasso for widget server.
Widget can be connected to any site over js include (<script...>)
With out this fix all dependences try loading from site, but not from my server widget.
I have tried put full url in urlPrefix, but serveStatic() won't work correctly.
This fix extracting only pathname from urlPrefix and putting to the routerPrefix.

**Comment by patrick-steele-idem** [comment]
Thank you for clarifying. Makes sense 👍

**Comment by FiW** [comment]
and.. marko & lasso are awesome! thank you very much, I love they from first look! ;-)

**Comment by austinkelleher** [comment]
@FiW Thanks a lot for this fix! I pulled down your branch, picked your commit, and fixed the merge conflicts. The reason for your conflict is because recently we made changes to support a dist folder, which would get served to Node 6 users. If you're on Node 8+, you will get the standard source code. We've moved the source code to the `src` directory.

Your commit landed here: https://github.com/lasso-js/lasso/commit/30fe2ba094d3972ea34836eb5381f949e83a9265
Published `lasso@3.0.0-beta.8`

Also backported your fixed to `lasso@2.11.17`.

**Pull request closed without merging**
