### PR TITLE
Fixes #93 - Update lasso to add support for CSP nonce

### LINKED ISSUE #93: Update lasso to add support for CSP nonce
Need to update lasso to support the nonce feature of Content Security Policy 2, for the script tags in the HTML.

Example:

```html
<script nonce="a613a14b8875acfa0fa40d2229d8786c9a5a2d260"> 
//JS Code 
</script>
```

### PR DESCRIPTION
**Pull request by patrick-steele-idem**

### CODE REVIEW

**Comment by ppattanayak** [comment]
Update working fine, using lasso-nonce as placeholder.

**Comment by tropperstyle** [comment]
Status update on this merge?

**Comment by patrick-steele-idem** [comment]
It needs to happen :) I'll work on that now. Thanks for the reminder. Work still needs to happen on the marko-widgets side...

**Comment by tropperstyle** [comment]
Ah okay thanks for the update

**Comment by patrick-steele-idem** [comment]
New version published: `lasso@1.15.0`

**Pull request merged**
