### PR TITLE
Fixed for Koajs

### PR DESCRIPTION
**Pull request by basickarl**
Fixed a tmp solution for working with Koajs.

### CODE REVIEW

**Comment by basickarl** [comment]
https://github.com/lasso-js/lasso/issues/161

**Comment by patrick-steele-idem** [comment]
Part of me wonders if we should export a separate set of middleware for koa to be a little more future proof:

```javascript
require('lasso/middleware/koa').serveStatic();
```

Thoughts?

**Comment by basickarl** [comment]
@patrick-steele-idem I do think that is wise. Since Koa and Express seem to be taking different paths and would seem less messy code wise. 
```
require('lasso/middleware/koa').serveStatic();
```
Sounds good!

**Comment by patrick-steele-idem** [comment]
Great. Do you mind updating your PR to go that route? Thanks!

**Comment by basickarl** [comment]
@patrick-steele-idem There we go, fixed. Also updated version of Lasso to 2.5.9.

**Pull request merged**
